### ISSUE TITLE
生成的xray配置文件，有一处错误

### ISSUE THREAD

**Issue by hkbase** [ArchiveNetwork/wgcf-cli#1]
#cat wgcf.json.xray.json
执行上面的命令查看wgcf-cli生成的xray配置文件，发现有一处错误：
{ 
   "protocol": "xray",
......
}
这个protocol的值应该是wireguard

**Comment by chise0713** [comment]
fbe1630161e96424a82f910be95ba6042ab3f9aa

**Comment by chise0713** [comment]
[fbe1630](https://github.com/chise0713/wgcf-cli/commit/fbe1630161e96424a82f910be95ba6042ab3f9aa)
[tag/23.12.16](https://github.com/chise0713/wgcf-cli/releases/tag/23.12.16)

**Comment by hkbase** [comment]
在我手动修正上面的错误后，该配置文件在最新的xray v1.8.6版本中依旧不可用
还需要在配置文件中添加下面这个参数后，才可以正常运行
"kernelMode": false

**Comment by chise0713** [comment]
这个就自己改了再放到配置文件里吧，我就不加在自动生成里了。

**Comment by saqie1393** [comment]
how to add in v2rayNG always say invalid?
