### ISSUE TITLE
`-g wg` 生成的配置在OpenWRT下无法执行

### ISSUE THREAD

**Issue by xionglingfeng** [ArchiveNetwork/wgcf-cli#13]
`-g wg` 命令生成了两个文件。其中 `wgcf.nft.conf` 可以在OpenWRT下正确执行。
`wgcf.ini.wgcf.conf`中包含的 PreUp PostUp 脚本引用了iptables命令，在OpenWRT下是无法运行的（iptables已经移除并改为使用nft）。
同时，`ip rule add oif XXX`会报错：
```
ip: invalid argument ‘oif’ to ‘ip’
```

**Comment by chise0713** [comment]
请安装 iptables-nft 转译
请检查 iproute2 的版本

**Comment by xionglingfeng** [comment]
iptables-nft 应该可以解决第一个问题
iproute2好像在OpenWRT里没有对应的包… OpenWRT的ip命令是busybox提供的

**Comment by xionglingfeng** [comment]
刚试了一下，安装 `iptables-nft` 和 `ip-tiny` 之后，所有的命令就都可以执行啦～

但是，OpenWRT下好像没有办法写PreUp/PostUp之类的hook。

我在 `luci` 配置好WireGuard接口之后，手动执行了PreUp/PostUp命令，同时执行了`wgcf.nft.conf`，但是WireGuard接口始终显示 `0 RX`，然后WireGuard页面显示Peer的handshake是 `Never` 。

我在nft规则之后加了 `counter` 可以看到 `set $routing_id` 这一句是执行了的

请问可能是哪里不对呢……？

**Comment by chise0713** [comment]
使用以下命令打开 wireguard 的调试日志输出
```bash
echo module wireguard +p > /sys/kernel/debug/dynamic_debug/control
```
然后 `dmesg -w`，查看是否有 `Sending handshake initiation to peer xxx` ；

或者使用 `tcpdump -i any port 2408 and ip [endpoint]` 抓包查看握手情况。

当然也有可能是目标 endpoint 被中间人黑洞了，尝试使用 [/scripts](https://github.com/ArchiveNetwork/wgcf-cli/tree/master/scripts) 中的 `endpoint.sh` 进行自动 endpoint 选择，不过我并不使用 OpenWRT，脚本可能需要进行一些修改。

> 但是，OpenWRT下好像没有办法写PreUp/PostUp之类的hook。

关于这点，可以将 `wg-quick` 脚本更换为官方的[最新脚本](https://github.com/WireGuard/wireguard-tools/blob/master/src/wg-quick/linux.bash)。

**Comment by charliez0** [comment]
。

**Comment by charliez0** [comment]
.
