### ISSUE TITLE
默认生成的账号为非plus账号

### ISSUE THREAD

**Issue by hkbase** [ArchiveNetwork/wgcf-cli#2]
#cat wgcf.json
......
"warp_plus": true,
......

查看默认生成的账号信息，里面有一处信息显示如上，说明是plus账号，但在使用生成的xray配置文件后，
#curl https://www.cloudflare.com/cdn-cgi/trace
......
warp=on
.......
最终确认又是非plus账号，前面的显示与最终的结果不一致。

**Comment by chise0713** [comment]
```bash
    curl -X POST 'https://api.cloudflareclient.com/v0a2158/reg' -sL --tlsv1.3 \
    -H 'CF-Client-Version: a-7.21-0721' -H 'Content-Type: application/json' \
    -d \
   '{
        "key":"'$(openssl rand -base64 32)'",
        "tos":"'$(date +"%Y-%m-%dT%H:%M:%S.000Z")'"
    }' \
        | python3 -m json.tool 
```
它的"warp_plus"返回值在注册时始终是true，可以尝试上面的这段脚本。输出应该会是
> ......
>"warp_plus": true,
>......

**Comment by chise0713** [comment]
你应该查看 `account_type` 来判断是否为plus账户，它们分别为 `free` / `limited` / `unlimited` / `team` ，其中只有 `free` 在trace时返回的 `warp=` 值为 `on` 而不是 `plus` ，这个可能的“错误”是上游返回的，并不属于本项目的问题。

如果有其他问题，请随意提问，否则此issue将在24小时内关闭为 `won't fix` 。
