### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by xkajxkajx** [ArchiveNetwork/wgcf-cli#27]
Is it possible to change "Endpoint = 162.159.193.199:2408" to "Endpoint = engage.cloudflareclient.com:2408"
    in the "wgcf.ini.wgcf.conf" profile ?

*Suggestions:

    Could you add check account ( status ) to the command line?
    It's better to add "DNS = 1.1.1.1, 1.0.0.1 " line to "wgcf.ini.wgcf.conf" profile, isn't it?
    Is "https://github.com/ArchiveNetwork/wgcf-cli/blob/master/README.md" still valid or it needs updating ?

Thanks

**Comment by chise0713** [comment]
The generated file is just a template, you can change it to what you want.

> Could you add check account ( status ) to the command line?

What status check? Please be specific.

**Comment by xkajxkajx** [comment]
Thanks for your response.
 
I think it is more easier if you add a command line **option** to change the Endpoint line to "Endpoint = engage.cloudflareclient.com '' instead of adding it manually.

 **Check account status** : like  ( id , account_type ,premium_data , warp_plus ,license key ......etc) .
This command is like the one in this tool: https://github.com/ViRb3/wgcf

wgcf .exe status

P.S. I know it is created in "wgcf.json" , but I would like to see it in the console command .
Of course I can do it with the command : type wgcf.json, but this is boring.

**Comment by chise0713** [comment]
> I think it is more easier if you add a command line **option** to change the Endpoint line to "Endpoint = engage.cloudflareclient.com '' instead of adding it manually.
 
In fact, the endpoint is the IPv4 address returned by the API, not hard-coded in the code.
So I belive it's better to use what the API returns, rather than using the DNS which may not be reliable.
If you want to use domain instead IP, you can always change it by yourself.

> **Check account status** : like ( id , account_type ,premium_data , warp_plus ,license key ......etc) .

This is a good suggestion, it is now planned.
