### ISSUE TITLE
About the new " v0.3.6"

### ISSUE THREAD

**Issue by xkajxkajx** [ArchiveNetwork/wgcf-cli#30]
About the "Check account status " issue ,I know it is human readable  but I said  IT IS MORE EASIER to check it and see it after running the command "wgcf-cli.exe update" as in the tool " wgcf.exe".

About the new " v0.3.6"
With all due respect ,I think you are making things more complicated by changing the options in the console command.

For instance , You have changed the command (wgcf-cli.exe  -l "LICENSE KEY" )  to ( wgcf-cli.exe license -l "LICENSE KEY").

When I run " wgcf-cli.exe generate --wg" I'm getting "wgcf.ini" which is the same as "wgcf.ini.wgcf.conf" with different extension. How to make "wgcf.ini.wgcf.conf" directly?

Every time I run wgcf-cli.exe, it makes "wgcf.nft.conf"  with the same and unchangeable contents by default. 
Can I change "ip daddr 162.159.193.199 udp dport 2408" to  "ip daddr 162.159.193.1 udp dport 2408" or something else and make it as a default one?

You should elaborate a little bit  in the last "README.md " file and give some more command examples.

**Comment by chise0713** [comment]
> About the "Check account status " issue ,I know it is human readable but I said IT IS MORE EASIER to check it and see it after running the command "wgcf-cli.exe update" as in the tool " wgcf.exe".

Okay, what field you want to display when do update?
```console
=======================================
Device name   : E6DBA7
Device model  : PC
Device active : true
Account type  : free
Role          : child
Premium data  : 0.00 B
Quota         : 0.00 B
=======================================
```
Like this?

> For instance , You have changed the command (wgcf-cli.exe -l "LICENSE KEY" ) to ( wgcf-cli.exe license -l "LICENSE KEY").

> You should elaborate a little bit in the last "README.md " file and give some more command examples.

Well, 0.2 and 0.3 are completely different thing. The 0.3 version is built using cobra, so you can use sub-command `help` or `--help/-h` flag for usage, for example `wgcf-cli generate --help`. If you are using bash/zsh/fish/pwsh, cobra can also generate an auto-completion file for them.

```console
~$ wgcf-cli completion -h
Generate the autocompletion script for wgcf-cli for the specified shell.
See each sub-command's help for details on how to use the generated script.

Usage:
  wgcf-cli completion [command]

Available Commands:
  bash        Generate the autocompletion script for bash
  fish        Generate the autocompletion script for fish
  powershell  Generate the autocompletion script for powershell
  zsh         Generate the autocompletion script for zsh

Flags:
  -h, --help   help for completion

Global Flags:
  -c, --config string   set configuration file path (default "wgcf.json")

Use "wgcf-cli completion [command] --help" for more information about a command.

```

> How to make "wgcf.ini.wgcf.conf" directly?

I don't understand this.

> Every time I run wgcf-cli.exe, it makes "wgcf.nft.conf" with the same and unchangeable contents by default.
Can I change "ip daddr 162.159.193.199 udp dport 2408" to "ip daddr 162.159.193.1 udp dport 2408" or something else and make it as a default one?

The 0.2 version's wgcf.nft.conf is for the reserved field, now that field is no longer needed, so I removed this feature.

**Comment by xkajxkajx** [comment]
Yes, these are the  basic fields. 
And I would be grateful If you add these fields:
 "warp_plus": true/false  
"created": "DATE & TIME"
"license": "xxxxxxxxxxxxxxxxxxxxxx" 

 "**How to make "wgcf.ini.wgcf.conf**" directly?" means making a default WireGuard configuration file with the extension (.conf).

As I said When I run " wgcf-cli.exe generate --wg" I'm getting only "wgcf.ini"  but not a (.conf) file.

 I hope you get the idea !

THANX
